version: '3.8'

networks:
  frontend:
  backend:

services:

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env 
    volumes:
      - "./backend/app:/code/app"
    command: uvicorn app.main:app --root-path /api --proxy-headers --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - database

  frontend:
    build: ./front
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - backend

  database:
    image: postgres
    container_name: postgres_db_container
    ports:
      - "5432:5432"
    env_file:
      - .env 
    volumes:
      - db-volume:/var/lib/postgresql/data/ 

volumes:
  caddy-data:
  caddy-config:
  db-volume:
