version: '3.8'

services:

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - "./backend/app:/code/app"
    command: uvicorn app.main:app --root-path /api --proxy-headers --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./front
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - backend

volumes:
  caddy-data:
  caddy-config:
